
### Get Pokemon by name
GET http://localhost:3000/pokemon/ditto

### Post a New Pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "Perro",
    "type": "normal",
    "moves": ["transform", "Sleep"]
}

