### GET ALL MOVIES
GET http://localhost:3000/movies

### GET MOVIE BY ID
GET http://localhost:3000/movies/061bc6e8-616c-11ef-b766-7cd30a82d48b

### GET MOVIE BY GENRE
GET http://localhost:3000/movies?genre=Drama

### POST A NEW MOVIE
POST http://localhost:3000/movies
Content-Type: application/json

  {
    "title": "The Prestige",
    "year": 2006,
    "director": "Christopher Nolan",
    "duration": 130,
    "poster": "https://i.pinimg.com/564x/cc/95/79/cc95794114a7c07872c96338778d3bf9.jpg",
    "genre": ["Drama", "Mystery", "Thriller"],
    "rate": 8.5
  }


### UPDATE MOVIE BY ID

PATCH http://localhost:3000/movies/6b2b94fb-6174-11ef-b766-7cd30a82d48b
Content-Type: application/json

{
    "year": 1900
}

### DELETE MOVIE BY ID

DELETE http://localhost:3000/movies/5bab9c92-617c-11ef-b766-7cd30a82d48b


